# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/WIP_Portfolio/lib/ui/Validation_MainUI.ui',
# licensing of 'D:/WIP_Portfolio/lib/ui/Validation_MainUI.ui' applies.
#
# Created: Sat Nov 14 01:51:43 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindowValidation(object):
    def setupUi(self, MainWindowValidation):
        MainWindowValidation.setObjectName("MainWindowValidation")
        MainWindowValidation.resize(409, 864)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowValidation.sizePolicy().hasHeightForWidth())
        MainWindowValidation.setSizePolicy(sizePolicy)
        MainWindowValidation.setMinimumSize(QtCore.QSize(100, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindowValidation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 20))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbTitle = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.lbTitle.setFont(font)
        self.lbTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lbTitle.setObjectName("lbTitle")
        self.gridLayout_2.addWidget(self.lbTitle, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 401, 713))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(17, 700, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.lbValidationResult = QtWidgets.QLabel(self.centralwidget)
        self.lbValidationResult.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbValidationResult.setAutoFillBackground(False)
        self.lbValidationResult.setAlignment(QtCore.Qt.AlignCenter)
        self.lbValidationResult.setObjectName("lbValidationResult")
        self.verticalLayout_4.addWidget(self.lbValidationResult)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.btnSwapCheckUncheckAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnSwapCheckUncheckAll.setMinimumSize(QtCore.QSize(0, 35))
        self.btnSwapCheckUncheckAll.setStyleSheet("")
        self.btnSwapCheckUncheckAll.setCheckable(False)
        self.btnSwapCheckUncheckAll.setChecked(False)
        self.btnSwapCheckUncheckAll.setFlat(False)
        self.btnSwapCheckUncheckAll.setObjectName("btnSwapCheckUncheckAll")
        self.gridLayout.addWidget(self.btnSwapCheckUncheckAll, 0, 1, 1, 1)
        self.btnShowError = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowError.setMinimumSize(QtCore.QSize(0, 33))
        self.btnShowError.setMaximumSize(QtCore.QSize(10, 33))
        self.btnShowError.setStyleSheet("QPushButton { \n"
"   background-color: rgb(255, 0, 0);\n"
"    border: 0px;\n"
"}\n"
"")
        self.btnShowError.setText("")
        self.btnShowError.setCheckable(True)
        self.btnShowError.setFlat(False)
        self.btnShowError.setObjectName("btnShowError")
        self.gridLayout.addWidget(self.btnShowError, 0, 5, 1, 1)
        self.btnValidate = QtWidgets.QPushButton(self.centralwidget)
        self.btnValidate.setMinimumSize(QtCore.QSize(100, 35))
        self.btnValidate.setObjectName("btnValidate")
        self.gridLayout.addWidget(self.btnValidate, 0, 2, 1, 1)
        self.btnUncollapseAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnUncollapseAll.setMinimumSize(QtCore.QSize(30, 35))
        self.btnUncollapseAll.setCheckable(True)
        self.btnUncollapseAll.setDefault(False)
        self.btnUncollapseAll.setFlat(False)
        self.btnUncollapseAll.setObjectName("btnUncollapseAll")
        self.gridLayout.addWidget(self.btnUncollapseAll, 0, 4, 1, 1)
        self.btnResetAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnResetAll.setMinimumSize(QtCore.QSize(0, 33))
        self.btnResetAll.setMaximumSize(QtCore.QSize(10, 33))
        self.btnResetAll.setStyleSheet("QPushButton { \n"
"   background-color: grey;\n"
"    border: 0px;\n"
"}\n"
"")
        self.btnResetAll.setText("")
        self.btnResetAll.setFlat(False)
        self.btnResetAll.setObjectName("btnResetAll")
        self.gridLayout.addWidget(self.btnResetAll, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        MainWindowValidation.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindowValidation)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 409, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuPreset = QtWidgets.QMenu(self.menuBar)
        self.menuPreset.setObjectName("menuPreset")
        MainWindowValidation.setMenuBar(self.menuBar)
        self.actionShader_Library = QtWidgets.QAction(MainWindowValidation)
        self.actionShader_Library.setObjectName("actionShader_Library")
        self.actionBaking_AO = QtWidgets.QAction(MainWindowValidation)
        self.actionBaking_AO.setObjectName("actionBaking_AO")
        self.action = QtWidgets.QAction(MainWindowValidation)
        self.action.setObjectName("action")
        self.actionOpen_Preset_Folder = QtWidgets.QAction(MainWindowValidation)
        self.actionOpen_Preset_Folder.setObjectName("actionOpen_Preset_Folder")
        self.actionAdd_And_Save_Preset = QtWidgets.QAction(MainWindowValidation)
        self.actionAdd_And_Save_Preset.setObjectName("actionAdd_And_Save_Preset")
        self.menuFile.addAction(self.actionAdd_And_Save_Preset)
        self.menuFile.addAction(self.actionOpen_Preset_Folder)
        self.menuFile.addSeparator()
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuPreset.menuAction())

        self.retranslateUi(MainWindowValidation)
        QtCore.QMetaObject.connectSlotsByName(MainWindowValidation)

    def retranslateUi(self, MainWindowValidation):
        MainWindowValidation.setWindowTitle(QtWidgets.QApplication.translate("MainWindowValidation", "Validation Main Window", None, -1))
        self.lbTitle.setText(QtWidgets.QApplication.translate("MainWindowValidation", "Validation", None, -1))
        self.progressBar.setFormat(QtWidgets.QApplication.translate("MainWindowValidation", "%p%", None, -1))
        self.lbValidationResult.setText(QtWidgets.QApplication.translate("MainWindowValidation", "Validation Result !", None, -1))
        self.btnSwapCheckUncheckAll.setText(QtWidgets.QApplication.translate("MainWindowValidation", "Check\n"
"Uncheck", None, -1))
        self.btnShowError.setToolTip(QtWidgets.QApplication.translate("MainWindowValidation", "<html><head/><body><p><span style=\" font-size:10pt;\">Hiển thị tất cả danh sách phần tử của những mục sai</span></p></body></html>", None, -1))
        self.btnValidate.setToolTip(QtWidgets.QApplication.translate("MainWindowValidation", "<html><head/><body><p><span style=\" font-size:10pt;\">Tự động chạy tuần tự từ trên xuống dưới tất cả các mục check lỗi</span></p></body></html>", None, -1))
        self.btnValidate.setText(QtWidgets.QApplication.translate("MainWindowValidation", "Validate", None, -1))
        self.btnUncollapseAll.setText(QtWidgets.QApplication.translate("MainWindowValidation", "Collapse\n"
"Uncollapse", None, -1))
        self.btnResetAll.setToolTip(QtWidgets.QApplication.translate("MainWindowValidation", "<html><head/><body><p><span style=\" font-size:10pt;\">Hiển thị tất cả danh sách phần tử của những mục đúng</span></p></body></html>", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindowValidation", "File", None, -1))
        self.menuPreset.setTitle(QtWidgets.QApplication.translate("MainWindowValidation", "Load Preset", None, -1))
        self.actionShader_Library.setText(QtWidgets.QApplication.translate("MainWindowValidation", "Shader Library", None, -1))
        self.actionBaking_AO.setText(QtWidgets.QApplication.translate("MainWindowValidation", "Rigging Vehicle", None, -1))
        self.action.setText(QtWidgets.QApplication.translate("MainWindowValidation", "Add New...", None, -1))
        self.actionOpen_Preset_Folder.setText(QtWidgets.QApplication.translate("MainWindowValidation", "Open Preset Folder", None, -1))
        self.actionAdd_And_Save_Preset.setText(QtWidgets.QApplication.translate("MainWindowValidation", "Create New/ Save Preset", None, -1))

