# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Exporter_Add_ID.ui',
# licensing of 'D:\Exporter_Add_ID.ui' applies.
#
# Created: Mon Sep 23 16:51:46 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ExporterAddID(object):
    def setupUi(self, ExporterAddID):
        ExporterAddID.setObjectName("ExporterAddID")
        ExporterAddID.resize(476, 292)
        self.centralwidget = QtWidgets.QWidget(ExporterAddID)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 278, 229))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lvMaterials = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.lvMaterials.setMinimumSize(QtCore.QSize(260, 0))
        self.lvMaterials.setObjectName("lvMaterials")
        self.gridLayout_4.addWidget(self.lvMaterials, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.btnSetID = QtWidgets.QPushButton(self.centralwidget)
        self.btnSetID.setObjectName("btnSetID")
        self.gridLayout.addWidget(self.btnSetID, 0, 0, 1, 1)
        self.sbSetID = QtWidgets.QSpinBox(self.centralwidget)
        self.sbSetID.setMinimumSize(QtCore.QSize(50, 0))
        self.sbSetID.setMinimum(1)
        self.sbSetID.setProperty("value", 1)
        self.sbSetID.setObjectName("sbSetID")
        self.gridLayout.addWidget(self.sbSetID, 0, 1, 1, 1)
        self.btnSelectID = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectID.setObjectName("btnSelectID")
        self.gridLayout.addWidget(self.btnSelectID, 1, 0, 1, 1)
        self.sbSelectID = QtWidgets.QSpinBox(self.centralwidget)
        self.sbSelectID.setMinimumSize(QtCore.QSize(80, 0))
        self.sbSelectID.setMinimum(1)
        self.sbSelectID.setProperty("value", 1)
        self.sbSelectID.setObjectName("sbSelectID")
        self.gridLayout.addWidget(self.sbSelectID, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setMinimumSize(QtCore.QSize(0, 22))
        self.btn6.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn6.setObjectName("btn6")
        self.gridLayout_2.addWidget(self.btn6, 0, 5, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setMinimumSize(QtCore.QSize(0, 22))
        self.btn9.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn9.setObjectName("btn9")
        self.gridLayout_2.addWidget(self.btn9, 1, 1, 1, 1)
        self.btn12 = QtWidgets.QPushButton(self.centralwidget)
        self.btn12.setMinimumSize(QtCore.QSize(0, 22))
        self.btn12.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn12.setObjectName("btn12")
        self.gridLayout_2.addWidget(self.btn12, 1, 4, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setMinimumSize(QtCore.QSize(0, 22))
        self.btn1.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn1.setObjectName("btn1")
        self.gridLayout_2.addWidget(self.btn1, 0, 0, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setMinimumSize(QtCore.QSize(0, 22))
        self.btn2.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn2.setObjectName("btn2")
        self.gridLayout_2.addWidget(self.btn2, 0, 1, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setMinimumSize(QtCore.QSize(0, 22))
        self.btn3.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn3.setObjectName("btn3")
        self.gridLayout_2.addWidget(self.btn3, 0, 2, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setMinimumSize(QtCore.QSize(0, 22))
        self.btn5.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn5.setObjectName("btn5")
        self.gridLayout_2.addWidget(self.btn5, 0, 4, 1, 1)
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setMinimumSize(QtCore.QSize(0, 22))
        self.btn7.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn7.setObjectName("btn7")
        self.gridLayout_2.addWidget(self.btn7, 0, 6, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setMinimumSize(QtCore.QSize(0, 22))
        self.btn8.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn8.setObjectName("btn8")
        self.gridLayout_2.addWidget(self.btn8, 1, 0, 1, 1)
        self.btn13 = QtWidgets.QPushButton(self.centralwidget)
        self.btn13.setMinimumSize(QtCore.QSize(0, 22))
        self.btn13.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn13.setObjectName("btn13")
        self.gridLayout_2.addWidget(self.btn13, 1, 5, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setMinimumSize(QtCore.QSize(0, 22))
        self.btn4.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn4.setObjectName("btn4")
        self.gridLayout_2.addWidget(self.btn4, 0, 3, 1, 1)
        self.btn24 = QtWidgets.QPushButton(self.centralwidget)
        self.btn24.setMinimumSize(QtCore.QSize(0, 22))
        self.btn24.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn24.setObjectName("btn24")
        self.gridLayout_2.addWidget(self.btn24, 3, 2, 1, 1)
        self.btn30 = QtWidgets.QPushButton(self.centralwidget)
        self.btn30.setMinimumSize(QtCore.QSize(0, 22))
        self.btn30.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn30.setObjectName("btn30")
        self.gridLayout_2.addWidget(self.btn30, 4, 1, 1, 1)
        self.btn27 = QtWidgets.QPushButton(self.centralwidget)
        self.btn27.setMinimumSize(QtCore.QSize(0, 22))
        self.btn27.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn27.setObjectName("btn27")
        self.gridLayout_2.addWidget(self.btn27, 3, 5, 1, 1)
        self.btn39 = QtWidgets.QPushButton(self.centralwidget)
        self.btn39.setMinimumSize(QtCore.QSize(0, 22))
        self.btn39.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn39.setObjectName("btn39")
        self.gridLayout_2.addWidget(self.btn39, 5, 3, 1, 1)
        self.btn31 = QtWidgets.QPushButton(self.centralwidget)
        self.btn31.setMinimumSize(QtCore.QSize(0, 22))
        self.btn31.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn31.setObjectName("btn31")
        self.gridLayout_2.addWidget(self.btn31, 4, 2, 1, 1)
        self.btn28 = QtWidgets.QPushButton(self.centralwidget)
        self.btn28.setMinimumSize(QtCore.QSize(0, 22))
        self.btn28.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn28.setObjectName("btn28")
        self.gridLayout_2.addWidget(self.btn28, 3, 6, 1, 1)
        self.btn38 = QtWidgets.QPushButton(self.centralwidget)
        self.btn38.setMinimumSize(QtCore.QSize(0, 22))
        self.btn38.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn38.setObjectName("btn38")
        self.gridLayout_2.addWidget(self.btn38, 5, 2, 1, 1)
        self.btn21 = QtWidgets.QPushButton(self.centralwidget)
        self.btn21.setMinimumSize(QtCore.QSize(0, 22))
        self.btn21.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn21.setObjectName("btn21")
        self.gridLayout_2.addWidget(self.btn21, 2, 6, 1, 1)
        self.btn20 = QtWidgets.QPushButton(self.centralwidget)
        self.btn20.setMinimumSize(QtCore.QSize(0, 22))
        self.btn20.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn20.setObjectName("btn20")
        self.gridLayout_2.addWidget(self.btn20, 2, 5, 1, 1)
        self.btn35 = QtWidgets.QPushButton(self.centralwidget)
        self.btn35.setMinimumSize(QtCore.QSize(0, 22))
        self.btn35.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn35.setObjectName("btn35")
        self.gridLayout_2.addWidget(self.btn35, 4, 6, 1, 1)
        self.btn19 = QtWidgets.QPushButton(self.centralwidget)
        self.btn19.setMinimumSize(QtCore.QSize(0, 22))
        self.btn19.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn19.setObjectName("btn19")
        self.gridLayout_2.addWidget(self.btn19, 2, 4, 1, 1)
        self.btn36 = QtWidgets.QPushButton(self.centralwidget)
        self.btn36.setMinimumSize(QtCore.QSize(0, 22))
        self.btn36.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn36.setObjectName("btn36")
        self.gridLayout_2.addWidget(self.btn36, 5, 0, 1, 1)
        self.btn34 = QtWidgets.QPushButton(self.centralwidget)
        self.btn34.setMinimumSize(QtCore.QSize(0, 22))
        self.btn34.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn34.setObjectName("btn34")
        self.gridLayout_2.addWidget(self.btn34, 4, 5, 1, 1)
        self.btn26 = QtWidgets.QPushButton(self.centralwidget)
        self.btn26.setMinimumSize(QtCore.QSize(0, 22))
        self.btn26.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn26.setObjectName("btn26")
        self.gridLayout_2.addWidget(self.btn26, 3, 4, 1, 1)
        self.btn37 = QtWidgets.QPushButton(self.centralwidget)
        self.btn37.setMinimumSize(QtCore.QSize(0, 22))
        self.btn37.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn37.setObjectName("btn37")
        self.gridLayout_2.addWidget(self.btn37, 5, 1, 1, 1)
        self.btn41 = QtWidgets.QPushButton(self.centralwidget)
        self.btn41.setMinimumSize(QtCore.QSize(0, 22))
        self.btn41.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn41.setObjectName("btn41")
        self.gridLayout_2.addWidget(self.btn41, 5, 5, 1, 1)
        self.btn40 = QtWidgets.QPushButton(self.centralwidget)
        self.btn40.setMinimumSize(QtCore.QSize(0, 22))
        self.btn40.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn40.setObjectName("btn40")
        self.gridLayout_2.addWidget(self.btn40, 5, 4, 1, 1)
        self.btn42 = QtWidgets.QPushButton(self.centralwidget)
        self.btn42.setMinimumSize(QtCore.QSize(0, 22))
        self.btn42.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn42.setObjectName("btn42")
        self.gridLayout_2.addWidget(self.btn42, 5, 6, 1, 1)
        self.btn17 = QtWidgets.QPushButton(self.centralwidget)
        self.btn17.setMinimumSize(QtCore.QSize(0, 22))
        self.btn17.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn17.setObjectName("btn17")
        self.gridLayout_2.addWidget(self.btn17, 2, 2, 1, 1)
        self.btn16 = QtWidgets.QPushButton(self.centralwidget)
        self.btn16.setMinimumSize(QtCore.QSize(0, 22))
        self.btn16.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn16.setObjectName("btn16")
        self.gridLayout_2.addWidget(self.btn16, 2, 1, 1, 1)
        self.btn14 = QtWidgets.QPushButton(self.centralwidget)
        self.btn14.setMinimumSize(QtCore.QSize(0, 22))
        self.btn14.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn14.setObjectName("btn14")
        self.gridLayout_2.addWidget(self.btn14, 1, 6, 1, 1)
        self.btn15 = QtWidgets.QPushButton(self.centralwidget)
        self.btn15.setMinimumSize(QtCore.QSize(0, 22))
        self.btn15.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn15.setObjectName("btn15")
        self.gridLayout_2.addWidget(self.btn15, 2, 0, 1, 1)
        self.btn25 = QtWidgets.QPushButton(self.centralwidget)
        self.btn25.setMinimumSize(QtCore.QSize(0, 22))
        self.btn25.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn25.setObjectName("btn25")
        self.gridLayout_2.addWidget(self.btn25, 3, 3, 1, 1)
        self.btn32 = QtWidgets.QPushButton(self.centralwidget)
        self.btn32.setMinimumSize(QtCore.QSize(0, 22))
        self.btn32.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn32.setObjectName("btn32")
        self.gridLayout_2.addWidget(self.btn32, 4, 3, 1, 1)
        self.btn18 = QtWidgets.QPushButton(self.centralwidget)
        self.btn18.setMinimumSize(QtCore.QSize(0, 22))
        self.btn18.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn18.setObjectName("btn18")
        self.gridLayout_2.addWidget(self.btn18, 2, 3, 1, 1)
        self.btn29 = QtWidgets.QPushButton(self.centralwidget)
        self.btn29.setMinimumSize(QtCore.QSize(0, 22))
        self.btn29.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn29.setObjectName("btn29")
        self.gridLayout_2.addWidget(self.btn29, 4, 0, 1, 1)
        self.btn33 = QtWidgets.QPushButton(self.centralwidget)
        self.btn33.setMinimumSize(QtCore.QSize(0, 22))
        self.btn33.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn33.setObjectName("btn33")
        self.gridLayout_2.addWidget(self.btn33, 4, 4, 1, 1)
        self.btn10 = QtWidgets.QPushButton(self.centralwidget)
        self.btn10.setMinimumSize(QtCore.QSize(0, 22))
        self.btn10.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn10.setObjectName("btn10")
        self.gridLayout_2.addWidget(self.btn10, 1, 2, 1, 1)
        self.btn11 = QtWidgets.QPushButton(self.centralwidget)
        self.btn11.setMinimumSize(QtCore.QSize(0, 22))
        self.btn11.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn11.setObjectName("btn11")
        self.gridLayout_2.addWidget(self.btn11, 1, 3, 1, 1)
        self.btn23 = QtWidgets.QPushButton(self.centralwidget)
        self.btn23.setMinimumSize(QtCore.QSize(0, 22))
        self.btn23.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn23.setObjectName("btn23")
        self.gridLayout_2.addWidget(self.btn23, 3, 1, 1, 1)
        self.btn22 = QtWidgets.QPushButton(self.centralwidget)
        self.btn22.setMinimumSize(QtCore.QSize(0, 22))
        self.btn22.setMaximumSize(QtCore.QSize(22, 16777215))
        self.btn22.setObjectName("btn22")
        self.gridLayout_2.addWidget(self.btn22, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.btnRemoveID = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemoveID.setObjectName("btnRemoveID")
        self.gridLayout_3.addWidget(self.btnRemoveID, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        ExporterAddID.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ExporterAddID)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 476, 21))
        self.menubar.setObjectName("menubar")
        ExporterAddID.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ExporterAddID)
        self.statusbar.setObjectName("statusbar")
        ExporterAddID.setStatusBar(self.statusbar)

        self.retranslateUi(ExporterAddID)
        QtCore.QMetaObject.connectSlotsByName(ExporterAddID)

    def retranslateUi(self, ExporterAddID):
        ExporterAddID.setWindowTitle(QtWidgets.QApplication.translate("ExporterAddID", "Exporter Add ID", None, -1))
        self.btnSetID.setText(QtWidgets.QApplication.translate("ExporterAddID", "Set ID", None, -1))
        self.btnSelectID.setText(QtWidgets.QApplication.translate("ExporterAddID", "Select ID", None, -1))
        self.btn6.setText(QtWidgets.QApplication.translate("ExporterAddID", "6", None, -1))
        self.btn9.setText(QtWidgets.QApplication.translate("ExporterAddID", "9", None, -1))
        self.btn12.setText(QtWidgets.QApplication.translate("ExporterAddID", "12", None, -1))
        self.btn1.setText(QtWidgets.QApplication.translate("ExporterAddID", "1", None, -1))
        self.btn2.setText(QtWidgets.QApplication.translate("ExporterAddID", "2", None, -1))
        self.btn3.setText(QtWidgets.QApplication.translate("ExporterAddID", "3", None, -1))
        self.btn5.setText(QtWidgets.QApplication.translate("ExporterAddID", "5", None, -1))
        self.btn7.setText(QtWidgets.QApplication.translate("ExporterAddID", "7", None, -1))
        self.btn8.setText(QtWidgets.QApplication.translate("ExporterAddID", "8", None, -1))
        self.btn13.setText(QtWidgets.QApplication.translate("ExporterAddID", "13", None, -1))
        self.btn4.setText(QtWidgets.QApplication.translate("ExporterAddID", "4", None, -1))
        self.btn24.setText(QtWidgets.QApplication.translate("ExporterAddID", "24", None, -1))
        self.btn30.setText(QtWidgets.QApplication.translate("ExporterAddID", "30", None, -1))
        self.btn27.setText(QtWidgets.QApplication.translate("ExporterAddID", "27", None, -1))
        self.btn39.setText(QtWidgets.QApplication.translate("ExporterAddID", "39", None, -1))
        self.btn31.setText(QtWidgets.QApplication.translate("ExporterAddID", "31", None, -1))
        self.btn28.setText(QtWidgets.QApplication.translate("ExporterAddID", "28", None, -1))
        self.btn38.setText(QtWidgets.QApplication.translate("ExporterAddID", "38", None, -1))
        self.btn21.setText(QtWidgets.QApplication.translate("ExporterAddID", "21", None, -1))
        self.btn20.setText(QtWidgets.QApplication.translate("ExporterAddID", "20", None, -1))
        self.btn35.setText(QtWidgets.QApplication.translate("ExporterAddID", "35", None, -1))
        self.btn19.setText(QtWidgets.QApplication.translate("ExporterAddID", "19", None, -1))
        self.btn36.setText(QtWidgets.QApplication.translate("ExporterAddID", "36", None, -1))
        self.btn34.setText(QtWidgets.QApplication.translate("ExporterAddID", "34", None, -1))
        self.btn26.setText(QtWidgets.QApplication.translate("ExporterAddID", "26", None, -1))
        self.btn37.setText(QtWidgets.QApplication.translate("ExporterAddID", "37", None, -1))
        self.btn41.setText(QtWidgets.QApplication.translate("ExporterAddID", "41", None, -1))
        self.btn40.setText(QtWidgets.QApplication.translate("ExporterAddID", "40", None, -1))
        self.btn42.setText(QtWidgets.QApplication.translate("ExporterAddID", "42", None, -1))
        self.btn17.setText(QtWidgets.QApplication.translate("ExporterAddID", "17", None, -1))
        self.btn16.setText(QtWidgets.QApplication.translate("ExporterAddID", "16", None, -1))
        self.btn14.setText(QtWidgets.QApplication.translate("ExporterAddID", "14", None, -1))
        self.btn15.setText(QtWidgets.QApplication.translate("ExporterAddID", "15", None, -1))
        self.btn25.setText(QtWidgets.QApplication.translate("ExporterAddID", "25", None, -1))
        self.btn32.setText(QtWidgets.QApplication.translate("ExporterAddID", "32", None, -1))
        self.btn18.setText(QtWidgets.QApplication.translate("ExporterAddID", "18", None, -1))
        self.btn29.setText(QtWidgets.QApplication.translate("ExporterAddID", "29", None, -1))
        self.btn33.setText(QtWidgets.QApplication.translate("ExporterAddID", "33", None, -1))
        self.btn10.setText(QtWidgets.QApplication.translate("ExporterAddID", "10", None, -1))
        self.btn11.setText(QtWidgets.QApplication.translate("ExporterAddID", "11", None, -1))
        self.btn23.setText(QtWidgets.QApplication.translate("ExporterAddID", "23", None, -1))
        self.btn22.setText(QtWidgets.QApplication.translate("ExporterAddID", "22", None, -1))
        self.btnRemoveID.setText(QtWidgets.QApplication.translate("ExporterAddID", "Remove ID Selected", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExporterAddID = QtWidgets.QMainWindow()
    ui = Ui_ExporterAddID()
    ui.setupUi(ExporterAddID)
    ExporterAddID.show()
    sys.exit(app.exec_())

