# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/WIP_Portfolio/puzzle_maya/sbsar_mat_creation/ui/sbsar_mat_creation_ui.ui',
# licensing of 'D:/WIP_Portfolio/puzzle_maya/sbsar_mat_creation/ui/sbsar_mat_creation_ui.ui' applies.
#
# Created: Wed Apr 14 20:23:01 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SBSARMatCreationMainWindow(object):
    def setupUi(self, SBSARMatCreationMainWindow):
        SBSARMatCreationMainWindow.setObjectName("SBSARMatCreationMainWindow")
        SBSARMatCreationMainWindow.resize(743, 530)
        self.centralwidget = QtWidgets.QWidget(SBSARMatCreationMainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(743, 530))
        self.centralwidget.setMaximumSize(QtCore.QSize(743, 530))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lwThumbnailMatShowing = QtWidgets.QListWidget(self.centralwidget)
        self.lwThumbnailMatShowing.setResizeMode(QtWidgets.QListView.Adjust)
        self.lwThumbnailMatShowing.setViewMode(QtWidgets.QListView.IconMode)
        self.lwThumbnailMatShowing.setObjectName("lwThumbnailMatShowing")
        self.gridLayout_2.addWidget(self.lwThumbnailMatShowing, 5, 1, 1, 5)
        self.lbBakingSettings = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbBakingSettings.setFont(font)
        self.lbBakingSettings.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(85, 0, 0);")
        self.lbBakingSettings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbBakingSettings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbBakingSettings.setAlignment(QtCore.Qt.AlignCenter)
        self.lbBakingSettings.setObjectName("lbBakingSettings")
        self.gridLayout_2.addWidget(self.lbBakingSettings, 0, 0, 1, 6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gbMatLibrary = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gbMatLibrary.setFont(font)
        self.gbMatLibrary.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gbMatLibrary.setObjectName("gbMatLibrary")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbMatLibrary)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        self.btnCreateMat = QtWidgets.QPushButton(self.gbMatLibrary)
        self.btnCreateMat.setMinimumSize(QtCore.QSize(50, 50))
        self.btnCreateMat.setObjectName("btnCreateMat")
        self.gridLayout_3.addWidget(self.btnCreateMat, 2, 0, 1, 1)
        self.cbbMaterials = QtWidgets.QComboBox(self.gbMatLibrary)
        self.cbbMaterials.setObjectName("cbbMaterials")
        self.gridLayout_3.addWidget(self.cbbMaterials, 1, 0, 1, 1)
        self.lbMaterials = QtWidgets.QLabel(self.gbMatLibrary)
        self.lbMaterials.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbMaterials.setFont(font)
        self.lbMaterials.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.lbMaterials.setFrameShape(QtWidgets.QFrame.Box)
        self.lbMaterials.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbMaterials.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbMaterials.setObjectName("lbMaterials")
        self.gridLayout_3.addWidget(self.lbMaterials, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gbMatLibrary, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 5, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cbbBakeAO = QtWidgets.QCheckBox(self.centralwidget)
        self.cbbBakeAO.setObjectName("cbbBakeAO")
        self.horizontalLayout_8.addWidget(self.cbbBakeAO)
        self.cbbBakeCurvature = QtWidgets.QCheckBox(self.centralwidget)
        self.cbbBakeCurvature.setObjectName("cbbBakeCurvature")
        self.horizontalLayout_8.addWidget(self.cbbBakeCurvature)
        self.cbbBakeWorldSpaceNormal = QtWidgets.QCheckBox(self.centralwidget)
        self.cbbBakeWorldSpaceNormal.setObjectName("cbbBakeWorldSpaceNormal")
        self.horizontalLayout_8.addWidget(self.cbbBakeWorldSpaceNormal)
        self.cbbBakePosition = QtWidgets.QCheckBox(self.centralwidget)
        self.cbbBakePosition.setObjectName("cbbBakePosition")
        self.horizontalLayout_8.addWidget(self.cbbBakePosition)
        self.cbbBakeColorID = QtWidgets.QCheckBox(self.centralwidget)
        self.cbbBakeColorID.setObjectName("cbbBakeColorID")
        self.horizontalLayout_8.addWidget(self.cbbBakeColorID)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 7, 0, 1, 4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbOutputPath = QtWidgets.QLabel(self.centralwidget)
        self.lbOutputPath.setObjectName("lbOutputPath")
        self.horizontalLayout_7.addWidget(self.lbOutputPath)
        self.leOutputPath = QtWidgets.QLineEdit(self.centralwidget)
        self.leOutputPath.setObjectName("leOutputPath")
        self.horizontalLayout_7.addWidget(self.leOutputPath)
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBrowse.sizePolicy().hasHeightForWidth())
        self.btnBrowse.setSizePolicy(sizePolicy)
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout_7.addWidget(self.btnBrowse)
        self.gridLayout_6.addLayout(self.horizontalLayout_7, 6, 0, 1, 4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbAntiAlias = QtWidgets.QLabel(self.centralwidget)
        self.lbAntiAlias.setMinimumSize(QtCore.QSize(50, 0))
        self.lbAntiAlias.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbAntiAlias.setObjectName("lbAntiAlias")
        self.horizontalLayout_4.addWidget(self.lbAntiAlias)
        self.cbbAntiAlias = QtWidgets.QComboBox(self.centralwidget)
        self.cbbAntiAlias.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbbAntiAlias.setObjectName("cbbAntiAlias")
        self.horizontalLayout_4.addWidget(self.cbbAntiAlias)
        self.lbUvSet = QtWidgets.QLabel(self.centralwidget)
        self.lbUvSet.setMinimumSize(QtCore.QSize(50, 0))
        self.lbUvSet.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbUvSet.setObjectName("lbUvSet")
        self.horizontalLayout_4.addWidget(self.lbUvSet)
        self.cbbUvSet = QtWidgets.QComboBox(self.centralwidget)
        self.cbbUvSet.setObjectName("cbbUvSet")
        self.horizontalLayout_4.addWidget(self.cbbUvSet)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 4, 0, 1, 4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.leNormalMap = QtWidgets.QLineEdit(self.centralwidget)
        self.leNormalMap.setObjectName("leNormalMap")
        self.horizontalLayout_5.addWidget(self.leNormalMap)
        self.btnBrowseNormalMap = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowseNormalMap.setObjectName("btnBrowseNormalMap")
        self.horizontalLayout_5.addWidget(self.btnBrowseNormalMap)
        self.cbUseLowAsHigh = QtWidgets.QCheckBox(self.centralwidget)
        self.cbUseLowAsHigh.setObjectName("cbUseLowAsHigh")
        self.horizontalLayout_5.addWidget(self.cbUseLowAsHigh)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 5, 0, 1, 4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbWidth = QtWidgets.QLabel(self.centralwidget)
        self.lbWidth.setMinimumSize(QtCore.QSize(50, 0))
        self.lbWidth.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbWidth.setObjectName("lbWidth")
        self.horizontalLayout_3.addWidget(self.lbWidth)
        self.cbbWidth = QtWidgets.QComboBox(self.centralwidget)
        self.cbbWidth.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbbWidth.setObjectName("cbbWidth")
        self.horizontalLayout_3.addWidget(self.cbbWidth)
        self.lbHeight = QtWidgets.QLabel(self.centralwidget)
        self.lbHeight.setMinimumSize(QtCore.QSize(50, 0))
        self.lbHeight.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbHeight.setObjectName("lbHeight")
        self.horizontalLayout_3.addWidget(self.lbHeight)
        self.cbbHeight = QtWidgets.QComboBox(self.centralwidget)
        self.cbbHeight.setMinimumSize(QtCore.QSize(0, 0))
        self.cbbHeight.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbbHeight.setObjectName("cbbHeight")
        self.horizontalLayout_3.addWidget(self.cbbHeight)
        self.lbFormat = QtWidgets.QLabel(self.centralwidget)
        self.lbFormat.setMinimumSize(QtCore.QSize(50, 0))
        self.lbFormat.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbFormat.setObjectName("lbFormat")
        self.horizontalLayout_3.addWidget(self.lbFormat)
        self.cbbFormat = QtWidgets.QComboBox(self.centralwidget)
        self.cbbFormat.setObjectName("cbbFormat")
        self.horizontalLayout_3.addWidget(self.cbbFormat)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 2, 0, 1, 4)
        self.btnBakeMeshMaps = QtWidgets.QPushButton(self.centralwidget)
        self.btnBakeMeshMaps.setObjectName("btnBakeMeshMaps")
        self.gridLayout_6.addWidget(self.btnBakeMeshMaps, 8, 0, 1, 4)
        self.gridLayout_2.addLayout(self.gridLayout_6, 1, 0, 2, 6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lwSceneSBSARMatList = QtWidgets.QListWidget(self.centralwidget)
        self.lwSceneSBSARMatList.setObjectName("lwSceneSBSARMatList")
        self.verticalLayout.addWidget(self.lwSceneSBSARMatList)
        self.gridLayout_2.addLayout(self.verticalLayout, 6, 0, 1, 6)
        SBSARMatCreationMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SBSARMatCreationMainWindow)
        QtCore.QMetaObject.connectSlotsByName(SBSARMatCreationMainWindow)

    def retranslateUi(self, SBSARMatCreationMainWindow):
        SBSARMatCreationMainWindow.setWindowTitle(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "SBS Material Main Window", None, -1))
        self.lbBakingSettings.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Baking Settings", None, -1))
        self.gbMatLibrary.setTitle(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "SUBSTANCE MATERIAL LIBRARY", None, -1))
        self.btnCreateMat.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Click to Create", None, -1))
        self.lbMaterials.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Materials", None, -1))
        self.cbbBakeAO.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Bake AO", None, -1))
        self.cbbBakeCurvature.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Bake Curvature", None, -1))
        self.cbbBakeWorldSpaceNormal.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Bake World Space Normal", None, -1))
        self.cbbBakePosition.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Bake Position", None, -1))
        self.cbbBakeColorID.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Bake Color ID", None, -1))
        self.lbOutputPath.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Output Path", None, -1))
        self.btnBrowse.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Browse", None, -1))
        self.lbAntiAlias.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Anti-Alias", None, -1))
        self.lbUvSet.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "UV Set", None, -1))
        self.leNormalMap.setPlaceholderText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Load Normal Map", None, -1))
        self.btnBrowseNormalMap.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Browse", None, -1))
        self.cbUseLowAsHigh.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Use Low As High?", None, -1))
        self.lbWidth.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Width", None, -1))
        self.lbHeight.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Height", None, -1))
        self.lbFormat.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Format", None, -1))
        self.btnBakeMeshMaps.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "CLICK TO BAKE SELECTION!!!", None, -1))

