# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/WIP_Portfolio/puzzle_maya/sbsar_mat_creation/ui/sbsar_mat_creation_ui.ui',
# licensing of 'D:/WIP_Portfolio/puzzle_maya/sbsar_mat_creation/ui/sbsar_mat_creation_ui.ui' applies.
#
# Created: Thu Jun 17 00:36:04 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_SBSARMatCreationMainWindow(object):
    def setupUi(self, SBSARMatCreationMainWindow):
        SBSARMatCreationMainWindow.setObjectName("SBSARMatCreationMainWindow")
        SBSARMatCreationMainWindow.resize(828, 810)
        self.centralwidget = QtWidgets.QWidget(SBSARMatCreationMainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(743, 530))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbBakingSettings = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbBakingSettings.setFont(font)
        self.lbBakingSettings.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(85, 0, 0);")
        self.lbBakingSettings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbBakingSettings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbBakingSettings.setAlignment(QtCore.Qt.AlignCenter)
        self.lbBakingSettings.setObjectName("lbBakingSettings")
        self.gridLayout_2.addWidget(self.lbBakingSettings, 0, 0, 1, 2)
        self.twSwitchingTab = QtWidgets.QTabWidget(self.centralwidget)
        self.twSwitchingTab.setObjectName("twSwitchingTab")
        self.bakingTab = QtWidgets.QWidget()
        self.bakingTab.setObjectName("bakingTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.bakingTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbAntiAlias = QtWidgets.QLabel(self.bakingTab)
        self.lbAntiAlias.setMinimumSize(QtCore.QSize(50, 0))
        self.lbAntiAlias.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbAntiAlias.setObjectName("lbAntiAlias")
        self.horizontalLayout_4.addWidget(self.lbAntiAlias)
        self.cbbAntiAlias = QtWidgets.QComboBox(self.bakingTab)
        self.cbbAntiAlias.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbbAntiAlias.setObjectName("cbbAntiAlias")
        self.horizontalLayout_4.addWidget(self.cbbAntiAlias)
        self.lbUvSet = QtWidgets.QLabel(self.bakingTab)
        self.lbUvSet.setMinimumSize(QtCore.QSize(50, 0))
        self.lbUvSet.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbUvSet.setObjectName("lbUvSet")
        self.horizontalLayout_4.addWidget(self.lbUvSet)
        self.cbbUvSet = QtWidgets.QComboBox(self.bakingTab)
        self.cbbUvSet.setObjectName("cbbUvSet")
        self.horizontalLayout_4.addWidget(self.cbbUvSet)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbInputPath = QtWidgets.QLabel(self.bakingTab)
        self.lbInputPath.setObjectName("lbInputPath")
        self.gridLayout_4.addWidget(self.lbInputPath, 1, 0, 1, 1)
        self.leInputPath = QtWidgets.QLineEdit(self.bakingTab)
        self.leInputPath.setObjectName("leInputPath")
        self.gridLayout_4.addWidget(self.leInputPath, 1, 1, 1, 1)
        self.cbbUseUpperSettings = QtWidgets.QCheckBox(self.bakingTab)
        self.cbbUseUpperSettings.setObjectName("cbbUseUpperSettings")
        self.gridLayout_4.addWidget(self.cbbUseUpperSettings, 0, 0, 1, 2)
        self.lbInputName = QtWidgets.QLabel(self.bakingTab)
        self.lbInputName.setObjectName("lbInputName")
        self.gridLayout_4.addWidget(self.lbInputName, 2, 0, 1, 1)
        self.leInputName = QtWidgets.QLineEdit(self.bakingTab)
        self.leInputName.setObjectName("leInputName")
        self.gridLayout_4.addWidget(self.leInputName, 2, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 9, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 446, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 11, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbWidth = QtWidgets.QLabel(self.bakingTab)
        self.lbWidth.setMinimumSize(QtCore.QSize(50, 0))
        self.lbWidth.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbWidth.setObjectName("lbWidth")
        self.horizontalLayout_3.addWidget(self.lbWidth)
        self.cbbWidth = QtWidgets.QComboBox(self.bakingTab)
        self.cbbWidth.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbbWidth.setObjectName("cbbWidth")
        self.horizontalLayout_3.addWidget(self.cbbWidth)
        self.lbHeight = QtWidgets.QLabel(self.bakingTab)
        self.lbHeight.setMinimumSize(QtCore.QSize(50, 0))
        self.lbHeight.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbHeight.setObjectName("lbHeight")
        self.horizontalLayout_3.addWidget(self.lbHeight)
        self.cbbHeight = QtWidgets.QComboBox(self.bakingTab)
        self.cbbHeight.setMinimumSize(QtCore.QSize(0, 0))
        self.cbbHeight.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbbHeight.setObjectName("cbbHeight")
        self.horizontalLayout_3.addWidget(self.cbbHeight)
        self.lbFormat = QtWidgets.QLabel(self.bakingTab)
        self.lbFormat.setMinimumSize(QtCore.QSize(50, 0))
        self.lbFormat.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbFormat.setObjectName("lbFormat")
        self.horizontalLayout_3.addWidget(self.lbFormat)
        self.cbbFormat = QtWidgets.QComboBox(self.bakingTab)
        self.cbbFormat.setObjectName("cbbFormat")
        self.horizontalLayout_3.addWidget(self.cbbFormat)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.leNormalMap = QtWidgets.QLineEdit(self.bakingTab)
        self.leNormalMap.setObjectName("leNormalMap")
        self.horizontalLayout_9.addWidget(self.leNormalMap)
        self.btnBrowseNormalMap = QtWidgets.QPushButton(self.bakingTab)
        self.btnBrowseNormalMap.setObjectName("btnBrowseNormalMap")
        self.horizontalLayout_9.addWidget(self.btnBrowseNormalMap)
        self.cbUseLowAsHigh = QtWidgets.QCheckBox(self.bakingTab)
        self.cbUseLowAsHigh.setChecked(True)
        self.cbUseLowAsHigh.setObjectName("cbUseLowAsHigh")
        self.horizontalLayout_9.addWidget(self.cbUseLowAsHigh)
        self.gridLayout_6.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.btnBakeMeshMaps = QtWidgets.QPushButton(self.bakingTab)
        self.btnBakeMeshMaps.setObjectName("btnBakeMeshMaps")
        self.gridLayout_6.addWidget(self.btnBakeMeshMaps, 7, 0, 1, 1)
        self.btnCreateFileSBS = QtWidgets.QPushButton(self.bakingTab)
        self.btnCreateFileSBS.setObjectName("btnCreateFileSBS")
        self.gridLayout_6.addWidget(self.btnCreateFileSBS, 10, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbOutputPath = QtWidgets.QLabel(self.bakingTab)
        self.lbOutputPath.setObjectName("lbOutputPath")
        self.horizontalLayout_7.addWidget(self.lbOutputPath)
        self.leOutputPath = QtWidgets.QLineEdit(self.bakingTab)
        self.leOutputPath.setObjectName("leOutputPath")
        self.horizontalLayout_7.addWidget(self.leOutputPath)
        self.btnBrowse = QtWidgets.QPushButton(self.bakingTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBrowse.sizePolicy().hasHeightForWidth())
        self.btnBrowse.setSizePolicy(sizePolicy)
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout_7.addWidget(self.btnBrowse)
        self.gridLayout_6.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbOutputName = QtWidgets.QLabel(self.bakingTab)
        self.lbOutputName.setObjectName("lbOutputName")
        self.horizontalLayout_5.addWidget(self.lbOutputName)
        self.leOutputName = QtWidgets.QLineEdit(self.bakingTab)
        self.leOutputName.setObjectName("leOutputName")
        self.horizontalLayout_5.addWidget(self.leOutputName)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gbPreBake = QtWidgets.QGroupBox(self.bakingTab)
        self.gbPreBake.setFlat(False)
        self.gbPreBake.setObjectName("gbPreBake")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gbPreBake)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lbNote = QtWidgets.QLabel(self.gbPreBake)
        self.lbNote.setObjectName("lbNote")
        self.gridLayout_7.addWidget(self.lbNote, 0, 0, 1, 2)
        self.horizontalLayout_6.addWidget(self.gbPreBake)
        self.gridLayout_6.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cbbBakeAO = QtWidgets.QCheckBox(self.bakingTab)
        self.cbbBakeAO.setObjectName("cbbBakeAO")
        self.horizontalLayout_8.addWidget(self.cbbBakeAO)
        self.cbbBakeCurvature = QtWidgets.QCheckBox(self.bakingTab)
        self.cbbBakeCurvature.setObjectName("cbbBakeCurvature")
        self.horizontalLayout_8.addWidget(self.cbbBakeCurvature)
        self.cbbBakeWorldSpaceNormal = QtWidgets.QCheckBox(self.bakingTab)
        self.cbbBakeWorldSpaceNormal.setObjectName("cbbBakeWorldSpaceNormal")
        self.horizontalLayout_8.addWidget(self.cbbBakeWorldSpaceNormal)
        self.cbbBakePosition = QtWidgets.QCheckBox(self.bakingTab)
        self.cbbBakePosition.setObjectName("cbbBakePosition")
        self.horizontalLayout_8.addWidget(self.cbbBakePosition)
        self.cbbBakeColorID = QtWidgets.QCheckBox(self.bakingTab)
        self.cbbBakeColorID.setObjectName("cbbBakeColorID")
        self.horizontalLayout_8.addWidget(self.cbbBakeColorID)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.bakingTab)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 8, 0, 1, 1)
        self.twSwitchingTab.addTab(self.bakingTab, "")
        self.materialCreationTab = QtWidgets.QWidget()
        self.materialCreationTab.setObjectName("materialCreationTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.materialCreationTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.btnRefresh = QtWidgets.QPushButton(self.materialCreationTab)
        self.btnRefresh.setMinimumSize(QtCore.QSize(0, 50))
        self.btnRefresh.setObjectName("btnRefresh")
        self.gridLayout_8.addWidget(self.btnRefresh, 1, 1, 1, 1)
        self.lwObjectSBSARMatList = QtWidgets.QListWidget(self.materialCreationTab)
        self.lwObjectSBSARMatList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lwObjectSBSARMatList.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.lwObjectSBSARMatList.setIconSize(QtCore.QSize(128, 128))
        self.lwObjectSBSARMatList.setObjectName("lwObjectSBSARMatList")
        self.gridLayout_8.addWidget(self.lwObjectSBSARMatList, 1, 0, 1, 1)
        self.lwObjectSBSARWeatherEffectList = QtWidgets.QListWidget(self.materialCreationTab)
        self.lwObjectSBSARWeatherEffectList.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.lwObjectSBSARWeatherEffectList.setIconSize(QtCore.QSize(128, 128))
        self.lwObjectSBSARWeatherEffectList.setMovement(QtWidgets.QListView.Static)
        self.lwObjectSBSARWeatherEffectList.setFlow(QtWidgets.QListView.TopToBottom)
        self.lwObjectSBSARWeatherEffectList.setProperty("isWrapping", False)
        self.lwObjectSBSARWeatherEffectList.setResizeMode(QtWidgets.QListView.Fixed)
        self.lwObjectSBSARWeatherEffectList.setViewMode(QtWidgets.QListView.ListMode)
        self.lwObjectSBSARWeatherEffectList.setObjectName("lwObjectSBSARWeatherEffectList")
        self.gridLayout_8.addWidget(self.lwObjectSBSARWeatherEffectList, 1, 2, 1, 1)
        self.lbAssignedMaterials = QtWidgets.QLabel(self.materialCreationTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.lbAssignedMaterials.setFont(font)
        self.lbAssignedMaterials.setStyleSheet("background-color: rgb(85, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.lbAssignedMaterials.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbAssignedMaterials.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbAssignedMaterials.setAlignment(QtCore.Qt.AlignCenter)
        self.lbAssignedMaterials.setObjectName("lbAssignedMaterials")
        self.gridLayout_8.addWidget(self.lbAssignedMaterials, 0, 0, 1, 1)
        self.lbAssignedWeatherEffects = QtWidgets.QLabel(self.materialCreationTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.lbAssignedWeatherEffects.setFont(font)
        self.lbAssignedWeatherEffects.setStyleSheet("background-color: rgb(170, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.lbAssignedWeatherEffects.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbAssignedWeatherEffects.setAlignment(QtCore.Qt.AlignCenter)
        self.lbAssignedWeatherEffects.setObjectName("lbAssignedWeatherEffects")
        self.gridLayout_8.addWidget(self.lbAssignedWeatherEffects, 0, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_8, 2, 0, 1, 2)
        self.gbMatLibrary = QtWidgets.QGroupBox(self.materialCreationTab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gbMatLibrary.setFont(font)
        self.gbMatLibrary.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gbMatLibrary.setObjectName("gbMatLibrary")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbMatLibrary)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 5, 0, 1, 1)
        self.gbMaterials = QtWidgets.QGroupBox(self.gbMatLibrary)
        self.gbMaterials.setAutoFillBackground(False)
        self.gbMaterials.setStyleSheet("")
        self.gbMaterials.setFlat(False)
        self.gbMaterials.setCheckable(False)
        self.gbMaterials.setObjectName("gbMaterials")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbMaterials)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbbMaterials = QtWidgets.QComboBox(self.gbMaterials)
        self.cbbMaterials.setObjectName("cbbMaterials")
        self.verticalLayout_2.addWidget(self.cbbMaterials)
        self.btnCreateMat = QtWidgets.QPushButton(self.gbMaterials)
        self.btnCreateMat.setMinimumSize(QtCore.QSize(50, 50))
        self.btnCreateMat.setObjectName("btnCreateMat")
        self.verticalLayout_2.addWidget(self.btnCreateMat)
        self.gridLayout_3.addWidget(self.gbMaterials, 3, 0, 1, 1)
        self.gbWeatherEffects = QtWidgets.QGroupBox(self.gbMatLibrary)
        self.gbWeatherEffects.setObjectName("gbWeatherEffects")
        self.gridLayout = QtWidgets.QGridLayout(self.gbWeatherEffects)
        self.gridLayout.setObjectName("gridLayout")
        self.btnAssignWeatherEffects = QtWidgets.QPushButton(self.gbWeatherEffects)
        self.btnAssignWeatherEffects.setMinimumSize(QtCore.QSize(50, 50))
        self.btnAssignWeatherEffects.setObjectName("btnAssignWeatherEffects")
        self.gridLayout.addWidget(self.btnAssignWeatherEffects, 1, 0, 1, 1)
        self.cbbWeatherEffects = QtWidgets.QComboBox(self.gbWeatherEffects)
        self.cbbWeatherEffects.setObjectName("cbbWeatherEffects")
        self.gridLayout.addWidget(self.cbbWeatherEffects, 0, 0, 1, 1)
        self.btnRemoveWeatherEffects = QtWidgets.QPushButton(self.gbWeatherEffects)
        self.btnRemoveWeatherEffects.setMinimumSize(QtCore.QSize(50, 50))
        self.btnRemoveWeatherEffects.setObjectName("btnRemoveWeatherEffects")
        self.gridLayout.addWidget(self.btnRemoveWeatherEffects, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.gbWeatherEffects, 4, 0, 1, 1)
        self.gridLayout_5.addWidget(self.gbMatLibrary, 0, 0, 1, 1)
        self.lwThumbnailMatShowing = QtWidgets.QListWidget(self.materialCreationTab)
        self.lwThumbnailMatShowing.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lwThumbnailMatShowing.setIconSize(QtCore.QSize(128, 128))
        self.lwThumbnailMatShowing.setResizeMode(QtWidgets.QListView.Adjust)
        self.lwThumbnailMatShowing.setSpacing(0)
        self.lwThumbnailMatShowing.setViewMode(QtWidgets.QListView.IconMode)
        self.lwThumbnailMatShowing.setObjectName("lwThumbnailMatShowing")
        self.gridLayout_5.addWidget(self.lwThumbnailMatShowing, 0, 1, 1, 1)
        self.lbAddedMaterials = QtWidgets.QLabel(self.materialCreationTab)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbAddedMaterials.setFont(font)
        self.lbAddedMaterials.setStyleSheet("background-color: rgb(170, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.lbAddedMaterials.setFrameShape(QtWidgets.QFrame.Box)
        self.lbAddedMaterials.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbAddedMaterials.setLineWidth(2)
        self.lbAddedMaterials.setAlignment(QtCore.Qt.AlignCenter)
        self.lbAddedMaterials.setObjectName("lbAddedMaterials")
        self.gridLayout_5.addWidget(self.lbAddedMaterials, 1, 0, 1, 2)
        self.twSwitchingTab.addTab(self.materialCreationTab, "")
        self.gridLayout_2.addWidget(self.twSwitchingTab, 1, 0, 1, 2)
        SBSARMatCreationMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SBSARMatCreationMainWindow)
        self.twSwitchingTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SBSARMatCreationMainWindow)

    def retranslateUi(self, SBSARMatCreationMainWindow):
        SBSARMatCreationMainWindow.setWindowTitle(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "SBS Material Main Window", None, -1))
        self.lbBakingSettings.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Substance Automation Tools", None, -1))
        self.lbAntiAlias.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Anti-Alias", None, -1))
        self.lbUvSet.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "UV Set", None, -1))
        self.lbInputPath.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Input Path", None, -1))
        self.cbbUseUpperSettings.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Use Upper Settings ?", None, -1))
        self.lbInputName.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Input Name", None, -1))
        self.lbWidth.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Width", None, -1))
        self.lbHeight.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Height", None, -1))
        self.lbFormat.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Format", None, -1))
        self.leNormalMap.setPlaceholderText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Load Normal Map", None, -1))
        self.btnBrowseNormalMap.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Browse", None, -1))
        self.cbUseLowAsHigh.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Use Low As High?", None, -1))
        self.btnBakeMeshMaps.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "CLICK TO BAKE SELECTION!!!", None, -1))
        self.btnCreateFileSBS.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "CREATE FILE SBS !!!", None, -1))
        self.lbOutputPath.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Output Path", None, -1))
        self.btnBrowse.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Browse", None, -1))
        self.lbOutputName.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Output Name", None, -1))
        self.gbPreBake.setTitle(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Pre-Baking", None, -1))
        self.lbNote.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "If you have a low and high poly. Please select bake normal. High poly meshes should be put in HighPoly group\n"
"low poly meshes should be put in LowPoly group", None, -1))
        self.cbbBakeAO.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Bake AO", None, -1))
        self.cbbBakeCurvature.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Bake Curvature", None, -1))
        self.cbbBakeWorldSpaceNormal.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Bake World Space Normal", None, -1))
        self.cbbBakePosition.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Bake Position", None, -1))
        self.cbbBakeColorID.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Bake Color ID", None, -1))
        self.twSwitchingTab.setTabText(self.twSwitchingTab.indexOf(self.bakingTab), QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Mesh Baking", None, -1))
        self.btnRefresh.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Refresh", None, -1))
        self.lbAssignedMaterials.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Assigned Materials", None, -1))
        self.lbAssignedWeatherEffects.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Assigned Weather Effects", None, -1))
        self.gbMatLibrary.setTitle(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "SUBSTANCE MATERIAL LIBRARY", None, -1))
        self.gbMaterials.setTitle(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Materials", None, -1))
        self.btnCreateMat.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Click to Create and\n"
" Assign To Selection", None, -1))
        self.gbWeatherEffects.setTitle(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Weather Effects", None, -1))
        self.btnAssignWeatherEffects.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Click to Add", None, -1))
        self.btnRemoveWeatherEffects.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Click to Remove\n"
"From Selection", None, -1))
        self.lbAddedMaterials.setText(QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Substance Materials Of Selected Objects", None, -1))
        self.twSwitchingTab.setTabText(self.twSwitchingTab.indexOf(self.materialCreationTab), QtWidgets.QApplication.translate("SBSARMatCreationMainWindow", "Material Creation", None, -1))

